### ISSUE TITLE
Solution for an A6000 GPU

### ISSUE THREAD

**Issue by hshreeshail** [davidstutz/opencv-2.4-cuda-9-patch#2]
I am working with NVIDIA A6000 gpu which is of the "Ampere" architecture. Your `set(_generations)` command does not include this architecture. Could you please help me with what `set(__cuda_arch_bin)`  command to add to the `if else` block to handle this case?
Thanks.

**Comment by davidstutz** [comment]
Sorry I am not up-to-date on recent architectures. But I remember that NVIDIA had lists mapping GPUs to their respective architecture to be used in the CMAKE file.
